# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - expensetrackerApi

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore src/ExpenseTrackerApi/ExpenseTrackerApi.csproj

      - name: Build
        run: dotnet build src/ExpenseTrackerApi/ExpenseTrackerApi.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/ExpenseTrackerApi/ExpenseTrackerApi.csproj --configuration Release --no-build --output ./myapp

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9997E1953FC542D9ABBFFB1E74F7FFBA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3620541E14684F9A8A4581B3F97759D8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C0B401EE23DD4305B9BEB9A1E8CA75AF }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'expensetrackerAPi'
          package: .
